pipeline:
  build:
    image: node:20
    commands:
      - npm install
      - npm run build

  test:
    image: node:20
    commands:
      - npm install
      - npm test

  deploy:
    image: node:20
    commands:
      - npm install
    when:
      branch: main