pipeline:
  build:
    image: node:20
    commands:
      - npm install

  test:
    image: node:20
    commands:
      - npm install

  deploy:
    image: node:20
    commands:
      - npm install
    when:
      branch: main